### ISSUE TITLE
Minor improvement of English language string.

### ISSUE THREAD

**Issue by germanvaleroelizondo** [moodleou/moodle-qtype_ddwtos#14]
Hi,
While I was checking the ddstos question type in Moodle 3.0rc1, I realized that the string pluginnameadding | qtype_ddwtos, which currently is "Adding a drag and drop into text" contrasts with all the other 'pluginnameadding' strings for all the Moodle (core and additional) question types,  as they all end with the word 'question' (except label, of course):

Adding a correct writing question,
Adding a Calculated question,
Adding an Essay question,
Adding a select missing words question,
Adding a Matching question,
Adding a Multiple choice question,
Adding an Opaque question,
Adding a STACK question,
Adding an OU multiple response question,
Adding a short answer question
...

So, I would dare to suggest you to please consider changing the pluginnameadding | qtype_ddwtos string into "Adding a drag and drop into text question", so as to align it with the other question types.

Thanks in advance for your help and congratulations on this nice question type addition to Moodle core

**Comment by timhunt** [comment]
This question type is now in Moodle core. Closing this.
